-- Chạy lần lượt từng khối lệnh bằng cách bôi đen khối đó và nhấn Ctrl+Enter
USE TuneVault;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MediaItems' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE [MediaItems] ADD IsActive bit NOT NULL DEFAULT 1;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Playlists' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE [Playlists] ADD IsActive bit NOT NULL DEFAULT 1;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Albums' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE [Albums] ADD IsActive bit NOT NULL DEFAULT 1;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Notifications' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE [Notifications] ADD IsActive bit NOT NULL DEFAULT 1;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Notifications' AND COLUMN_NAME = 'SenderId')
BEGIN
    ALTER TABLE [Notifications] ADD SenderId varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
END;