IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MediaItems' AND COLUMN_NAME = 'IsValid')
BEGIN
    ALTER TABLE [MediaItems] ADD IsValid bit NOT NULL CONSTRAINT DF_MediaItems_IsValid DEFAULT 0;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Playlists' AND COLUMN_NAME = 'ReleaseDate')
BEGIN
    ALTER TABLE [Playlists] ADD ReleaseDate datetime2 NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Playlists' AND COLUMN_NAME = 'ContentType')
BEGIN
    ALTER TABLE [Playlists] ADD ContentType tinyint NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Albums' AND COLUMN_NAME = 'IsPublic')
BEGIN
    ALTER TABLE [Albums] ADD IsPublic bit NOT NULL CONSTRAINT DF_Albums_IsPublic DEFAULT 1;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Albums' AND COLUMN_NAME = 'ReleaseDate')
BEGIN
    ALTER TABLE [Albums] ADD ReleaseDate datetime2 NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Albums' AND COLUMN_NAME = 'ContentType')
BEGIN
    ALTER TABLE [Albums] ADD ContentType tinyint NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Notifications' AND COLUMN_NAME = 'TargetType')
BEGIN
    ALTER TABLE [Notifications] ADD TargetType tinyint NULL;
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Notifications' AND COLUMN_NAME = 'TargetId')
BEGIN
    ALTER TABLE [Notifications] ADD TargetId varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
END;
